import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://recapp.uni-goettingen.de/activate?quiz=0d245a55-c334-4b4a-90be-f04f8ba40bb0');
  await page.getByRole('button', { name: 'Continue without login' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'New question' }).click();
  await page.getByRole('combobox').nth(1).selectOption('SINGLE');
  await page.getByRole('textbox', { name: 'Question' }).click();
  await page.getByRole('textbox', { name: 'Question' }).fill('question 1');
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('1');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('2');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('3');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('4');
  await page.getByRole('button', { name: 'Save question' }).click();
  await page.getByRole('button', { name: 'New question' }).click();
  await page.getByRole('combobox').nth(1).selectOption('SINGLE');
  await page.getByRole('textbox', { name: 'Question' }).click();
  await page.getByRole('textbox', { name: 'Question' }).fill('question 2');
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('1');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('2');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('3');
  await page.getByText('-OHT-002').click();
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('4');
  await page.getByRole('button', { name: 'Save question' }).click();
  await page.getByRole('button', { name: 'New question' }).click();
  await page.getByRole('combobox').nth(1).selectOption('SINGLE');
  await page.getByRole('textbox', { name: 'Question' }).click();
  await page.getByRole('textbox', { name: 'Question' }).fill('question 3');
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('1');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('2');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('3');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('4');
  await page.getByRole('button', { name: 'Save question' }).click();
  await page.getByRole('button', { name: 'New question' }).click();
  await page.getByRole('combobox').nth(1).selectOption('SINGLE');
  await page.getByRole('textbox', { name: 'Question' }).click();
  await page.getByRole('textbox', { name: 'Question' }).fill('question 4');
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('1');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('2');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('3');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('4');
  await page.getByRole('button', { name: 'Save question' }).click();
  await page.getByRole('button', { name: 'New question' }).click();
  await page.getByRole('combobox').nth(1).selectOption('SINGLE');
  await page.getByRole('textbox', { name: 'Question' }).click();
  await page.getByRole('textbox', { name: 'Question' }).fill('question 5');
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('1');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('2');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('3');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('4');
  await page.getByRole('button', { name: 'Save question' }).click();
  await page.getByRole('button', { name: 'New question' }).click();
  await page.getByRole('combobox').nth(1).selectOption('SINGLE');
  await page.getByRole('textbox', { name: 'Question' }).click();
  await page.getByRole('textbox', { name: 'Question' }).fill('question 6');
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('button', { name: 'Add answer' }).click();
  await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('checkbox').nth(1).click();
  await page.locator('.mb-2.mt-2 > .align-self-center').first().click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('1');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('2');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('3');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('4');
  await page.getByRole('button', { name: 'Save question' }).click();
});
