name: RECAPP deployment check

on:
  push:
    branches: [main, testing, production]
  pull_request:
    branches: [main, testing, production]
  workflow_dispatch:

jobs:
  deploy-recapp:
    runs-on: ubuntu-24.04

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: run deployment script
        run: sh deployment.sh $GITHUB_WORKSPACE force-build
