name: Jut a test

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-test-test
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to TEST-TEST
    runs-on: ubuntu-latest

    # Optional but recommended: add an environment gate
    # Create an environment named "test" in Settings → Environments and add required reviewers.
    environment:
      name: test-test

    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}

      - name: Add test server to known_hosts
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          HOST="${{ secrets.TEST_SERVER_HOST }}"
          PORT="${{ secrets.TEST_SERVER_PORT || '22' }}"
          # Collect common key types. Redirect stderr to avoid noisy output.
          ssh-keyscan -p "$PORT" -t ed25519 "$HOST" >> ~/.ssh/known_hosts 2>/dev/null
          ssh-keyscan -p "$PORT" -t ecdsa  "$HOST" >> ~/.ssh/known_hosts 2>/dev/null
          ssh-keyscan -p "$PORT" -t rsa    "$HOST" >> ~/.ssh/known_hosts 2>/dev/null
          chmod 600 ~/.ssh/known_hosts
      
      - name: just hello
        run: |
          ssh -p "${{ secrets.TEST_SERVER_PORT || '22' }}" \
            "${{ secrets.TEST_SERVER_USER }}@${{ secrets.TEST_SERVER_HOST }}" \
            -- /bin/bash --noprofile --norc -c \
            'echo "Helo world!"'
